"use client"
import './globals.css'
import { Plus_Jakarta_Sans } from 'next/font/google'
import Head from './head'
const pjs = Plus_Jakarta_Sans({ subsets: ['latin'] })
import { FooterBar, HeaderBar, LoadingBox } from '../components'
import NextNProgress from 'nextjs-progressbar';
import Cookies from 'js-cookie'
import { Suspense } from 'react'

export const metadata = {
  title: 'Job Finder',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
        <Head />
        <body className={pjs.className}>
          <HeaderBar  />
          {children}
          <FooterBar />
        </body>
    </html>
  )
}



// 